[project]
name = "booktree"
version = "1.0.0"
dependencies = [
  "httpx>=0.27.0",
  "langcodes>=3.4.0",
  "pathvalidate>=3.2.0",
  "Requests>=2.32.3",
  "thefuzz>=0.22.1"
]
[project.scripts]
booktree = "booktree.booktree:app"